import React from 'react'


const studentData = [
  {
    id: 1,
    name: "Aarav Sharma",
    rollNo: "ST101",
    email: "aarav@example.com",
    phone: "9876543210",
    course: "Full Stack Development",
    city: "Pune",
    age: 20,
    percentage: 88,
    skills: ["HTML", "CSS", "JavaScript"],
    status: "Active",
    favourite: true,
    img: "https://randomuser.me/api/portraits/men/1.jpg"
  },
  {
    id: 2,
    name: "Riya Patil",
    rollNo: "ST102",
    email: "riya@example.com",
    phone: "9876543211",
    course: "Java Development",
    city: "Mumbai",
    age: 21,
    percentage: 91,
    skills: ["Java", "Spring Boot"],
    status: "Active",
    favourite: false,
    img: "https://randomuser.me/api/portraits/women/2.jpg"
  },
  {
    id: 3,
    name: "Aditya Joshi",
    rollNo: "ST103",
    email: "aditya@example.com",
    phone: "9876543212",
    course: "Python Development",
    city: "Nashik",
    age: 22,
    percentage: 84,
    skills: ["Python", "Django"],
    status: "Inactive",
    favourite: false,
    img: "https://randomuser.me/api/portraits/men/3.jpg"
  },
  {
    id: 4,
    name: "Sneha Kulkarni",
    rollNo: "ST104",
    email: "sneha@example.com",
    phone: "9876543213",
    course: "Data Science",
    city: "Nagpur",
    age: 20,
    percentage: 95,
    skills: ["Python", "Pandas"],
    status: "Active",
    favourite: true,
    img: "https://randomuser.me/api/portraits/women/4.jpg"
  },
  {
    id: 5,
    name: "Rohan Deshmukh",
    rollNo: "ST105",
    email: "rohan@example.com",
    phone: "9876543214",
    course: "MERN Stack",
    city: "Aurangabad",
    age: 23,
    percentage: 80,
    skills: ["React", "Node.js"],
    status: "Inactive",
    favourite: false,
    img: "https://randomuser.me/api/portraits/men/5.jpg"
  },
  {
    id: 6,
    name: "Priya Shinde",
    rollNo: "ST106",
    email: "priya@example.com",
    phone: "9876543215",
    course: "UI/UX Design",
    city: "Kolhapur",
    age: 21,
    percentage: 87,
    skills: ["Figma", "Adobe XD"],
    status: "Active",
    favourite: true,
    img: "https://randomuser.me/api/portraits/women/6.jpg"
  },
  {
    id: 7,
    name: "Kunal Pawar",
    rollNo: "ST107",
    email: "kunal@example.com",
    phone: "9876543216",
    course: "Cyber Security",
    city: "Solapur",
    age: 22,
    percentage: 78,
    skills: ["Networking", "Linux"],
    status: "Inactive",
  favourite: false,
    img: "https://randomuser.me/api/portraits/men/7.jpg"
  },
  {
    id: 8,
    name: "Neha Jadhav",
    rollNo: "ST108",
    email: "neha@example.com",
    phone: "9876543217",
    course: "Cloud Computing",
    city: "Satara",
    age: 20,
    percentage: 89,
    skills: ["AWS", "Docker"],
    status: "Active",
    favourite: true,
    img: "https://randomuser.me/api/portraits/women/8.jpg"
  },
  {
    id: 9,
    name: "Siddharth More",
    rollNo: "ST109",
    email: "sid@example.com",
    phone: "9876543218",
    course: "Machine Learning",
    city: "Ahmednagar",
    age: 23,
    percentage: 93,
    skills: ["Python", "TensorFlow"],
    status: "Active",
    favourite: false,
    img: "https://randomuser.me/api/portraits/men/9.jpg"
  },
  {
    id: 10,
    name: "Anjali Chavan",
    rollNo: "ST110",
    email: "anjali@example.com",
    phone: "9876543219",
    course: "Android Development",
    city: "Latur",
    age: 21,
    percentage: 85,
    skills: ["Kotlin", "Firebase"],
    status: "Inactive",
    favourite: true,
    img: "https://randomuser.me/api/portraits/women/10.jpg"
  },
  {
    id: 11,
    name: "Vishal Patil",
    rollNo: "ST111",
    email: "vishal@example.com",
    phone: "9876543220",
    course: "React Development",
    city: "Pune",
    age: 22,
    percentage: 90,
    skills: ["React", "Redux"],
    status: "Active",
    favourite: false,
    img: "https://randomuser.me/api/portraits/men/11.jpg"
  },
  {
    id: 12,
    name: "Pooja Gaikwad",
    rollNo: "ST112",
    email: "pooja@example.com",
    phone: "9876543221",
    course: "Web Development",
    city: "Jalna",
    age: 20,
    percentage: 86,
    skills: ["HTML", "CSS", "JavaScript"],
    status: "Inactive",
    favourite: true,
    img: "https://randomuser.me/api/portraits/women/12.jpg"
  },
  {
    id: 13,
    name: "Rahul Wagh",
    rollNo: "ST113",
    email: "rahul@example.com",
    phone: "9876543222",
    course: "PHP Development",
    city: "Beed",
    age: 24,
    percentage: 79,
    skills: ["PHP", "Laravel"],
    status: "Active",
    favourite: false,
    img: "https://randomuser.me/api/portraits/men/13.jpg"
  },
  {
    id: 14,
    name: "Kavya More",
    rollNo: "ST114",
    email: "kavya@example.com",
    phone: "9876543223",
    course: "Software Testing",
    city: "Sangli",
    age: 21,
    percentage: 92,
    skills: ["Selenium", "Manual Testing"],
    status: "Active",
    favourite: true,
    img: "https://randomuser.me/api/portraits/women/14.jpg"
  },
  {
    id: 15,
    name: "Omkar Kale",
    rollNo: "ST115",
    email: "omkar@example.com",
    phone: "9876543224",
    course: "DevOps",
    city: "Nanded",
    age: 22,
    percentage: 83,
    skills: ["Docker", "Kubernetes"],
    status: "Inactive",
    favourite: false,
    img: "https://randomuser.me/api/portraits/men/15.jpg"
  }
];
function Students() {
  return (
    <>
    
    </>
  )
}

export default studentData